# SPDX-License-Identifier: EPL-2.0
#
# Capture the directory of this file at include time.
# CMAKE_CURRENT_LIST_DIR inside a function resolves at *call* time
# (picks up the caller's directory), so we snapshot it here.
set(_ALEMBIC_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")

# alembic_add_patch(target_name cpp_file metadata_dir)
#
# Compiles a single Faust-generated CLAP C++ file into a .clap plugin bundle.
#
# Arguments:
#   target_name   — cmake target name and plugin bundle base name
#   cpp_file      — absolute path to the <name>_clap.cpp generated by
#                   `faust -a clap-arch.cpp`
#   metadata_dir  — directory containing the generated plugin_metadata.h
#
# The output .clap lands in ${CMAKE_BINARY_DIR}/plugins/.
# On macOS: a proper bundle (MyPatch.clap/Contents/MacOS/MyPatch).
# On Linux:  a flat .so renamed to .clap.
#
# Requires these variables to be set in the parent scope:
#   FAUST_INCLUDE_DIR  — from `faust --includedir`
#   FAUST_ARCH_DIR     — from `faust --archdir`
#   clap_SOURCE_DIR    — populated by FetchContent for free-audio/clap
#   clap-helpers_SOURCE_DIR — populated by FetchContent for free-audio/clap-helpers

function(alembic_add_patch target_name cpp_file metadata_dir)

    add_library(${target_name} MODULE
        ${cpp_file}
        ${FAUST_ARCH_DIR}/clap/clap-helpers-impl.cpp
        ${_ALEMBIC_CMAKE_DIR}/faust-gui-stubs.cpp)

    target_include_directories(${target_name} PRIVATE
        ${FAUST_INCLUDE_DIR}
        ${clap_SOURCE_DIR}/include
        ${clap-helpers_SOURCE_DIR}/include
        ${metadata_dir})

    target_compile_features(${target_name} PRIVATE cxx_std_17)

    # Suppress warnings in Faust-generated code — it's not ours to fix.
    target_compile_options(${target_name} PRIVATE
        $<$<CXX_COMPILER_ID:GNU,Clang,AppleClang>:-w>)

    if(APPLE)
        set_target_properties(${target_name} PROPERTIES
            BUNDLE                              TRUE
            BUNDLE_EXTENSION                    "clap"
            MACOSX_BUNDLE_BUNDLE_NAME           "${target_name}"
            MACOSX_BUNDLE_GUI_IDENTIFIER        "org.nomos-studio.alembic.${target_name}"
            MACOSX_BUNDLE_SHORT_VERSION_STRING  "1.0"
            PREFIX                              ""
            SUFFIX                              "")
    else()
        # Linux: flat shared library with .clap extension.
        set_target_properties(${target_name} PROPERTIES
            PREFIX  ""
            SUFFIX  ".clap")
    endif()

    set_target_properties(${target_name} PROPERTIES
        LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/plugins")

endfunction()
